import type { GameConfig } from "./types";

export const DEFAULT_GAME_CONFIG: GameConfig = {
  version: "faithful-0.3-halifax-west-end",
  startDate: "1984-12-01",
  numTurns: 31,
  startCash: 2000,
  startDebt: 5500,
  startBank: 0,
  startHealth: 100,
  startHelpers: 8,
  baseSpace: 20,
  helperSpace: 10,
  debtInterest: 10,
  bankInterest: 5,
  playerArmor: 100,
  helperArmor: 50,
  fightTimeoutSeconds: 5,
  currency: {
    symbol: "$",
    prefix: true,
  },
  names: {
    helperSingular: "bitch",
    helperPlural: "bitches",
    gunSingular: "gun",
    gunPlural: "guns",
    drugSingular: "drug",
    drugPlural: "drugs",
    loanShark: "the Loan Shark",
    bank: "the Bank",
    gunShop: "Dan's House of Guns",
    roughPub: "the pub",
  },
  prices: {
    spy: 20000,
    tipoff: 10000,
    helperMin: 50000,
    helperMax: 150000,
  },
  drugsMeta: {
    expensiveMessageA: "Sorry, cops made a big %DRUG% bust! Prices are outrageous!",
    expensiveMessageB: "Buyers are paying ridiculous damn money for %DRUG%, eh!",
    cheapDivide: 4,
    expensiveMultiply: 4,
  },
  serviceLocations: {
    loanShark: "bronx",
    bank: "bronx",
    gunShop: "ghetto",
    roughPub: "ghetto",
  },
  locations: [
    { id: "bronx", name: "Bronx", policePresence: 10, minDrug: 7, maxDrug: 12 },
    { id: "ghetto", name: "Ghetto", policePresence: 5, minDrug: 8, maxDrug: 12 },
    { id: "central-park", name: "Central Park", policePresence: 15, minDrug: 6, maxDrug: 12 },
    { id: "manhattan", name: "Manhattan", policePresence: 90, minDrug: 4, maxDrug: 10 },
    { id: "coney-island", name: "Coney Island", policePresence: 20, minDrug: 6, maxDrug: 12 },
    { id: "brooklyn", name: "Brooklyn", policePresence: 70, minDrug: 4, maxDrug: 11 },
    { id: "queens", name: "Queens", policePresence: 50, minDrug: 6, maxDrug: 12 },
    { id: "staten-island", name: "Staten Island", policePresence: 20, minDrug: 6, maxDrug: 12 },
    { id: "west-end-halifax", name: "West End Halifax", policePresence: 12, minDrug: 6, maxDrug: 10 },
  ],
  drugs: [
    {
      id: "acid",
      name: "Acid",
      minPrice: 1000,
      maxPrice: 4400,
      cheap: true,
      expensive: false,
      cheapMessage: "The market is flooded with cheap home-made acid!",
    },
    {
      id: "cocaine",
      name: "Cocaine",
      minPrice: 15000,
      maxPrice: 29000,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "hashish",
      name: "Hashish",
      minPrice: 480,
      maxPrice: 1280,
      cheap: true,
      expensive: false,
      cheapMessage: "The Marrakesh Express has arrived!",
    },
    {
      id: "heroin",
      name: "Heroin",
      minPrice: 5500,
      maxPrice: 13000,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "ludes",
      name: "Ludes",
      minPrice: 11,
      maxPrice: 60,
      cheap: true,
      expensive: false,
      cheapMessage: "Rival drug dealers raided a pharmacy and are selling cheap ludes!",
    },
    {
      id: "mda",
      name: "MDA",
      minPrice: 1500,
      maxPrice: 4400,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "opium",
      name: "Opium",
      minPrice: 540,
      maxPrice: 1250,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "pcp",
      name: "PCP",
      minPrice: 1000,
      maxPrice: 2500,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "peyote",
      name: "Peyote",
      minPrice: 220,
      maxPrice: 700,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "shrooms",
      name: "Shrooms",
      minPrice: 630,
      maxPrice: 1300,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "speed",
      name: "Speed",
      minPrice: 90,
      maxPrice: 250,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "weed",
      name: "Weed",
      minPrice: 315,
      maxPrice: 890,
      cheap: true,
      expensive: false,
      cheapMessage: "Colombian freighter dusted the Coast Guard! Weed prices have bottomed out!",
    },
  ],
  guns: [
    { id: "baretta", name: "Baretta", price: 3000, space: 4, damage: 5 },
    { id: "38-special", name: ".38 Special", price: 3500, space: 4, damage: 9 },
    { id: "ruger", name: "Ruger", price: 2900, space: 4, damage: 4 },
    { id: "saturday-night-special", name: "Saturday Night Special", price: 3100, space: 4, damage: 7 },
  ],
  cops: [
    {
      id: "hardass",
      name: "Officer Hardass",
      deputyName: "deputy",
      deputiesName: "deputies",
      armor: 4,
      deputyArmor: 3,
      attackPenalty: 30,
      defendPenalty: 30,
      minDeputies: 2,
      maxDeputies: 8,
      gunId: "baretta",
      copGun: 1,
      deputyGun: 1,
    },
    {
      id: "bob",
      name: "Officer Bob",
      deputyName: "deputy",
      deputiesName: "deputies",
      armor: 15,
      deputyArmor: 4,
      attackPenalty: 30,
      defendPenalty: 20,
      minDeputies: 4,
      maxDeputies: 10,
      gunId: "baretta",
      copGun: 2,
      deputyGun: 1,
    },
    {
      id: "smith",
      name: "Agent Smith",
      deputyName: "cop",
      deputiesName: "cops",
      armor: 50,
      deputyArmor: 6,
      attackPenalty: 20,
      defendPenalty: 20,
      minDeputies: 6,
      maxDeputies: 18,
      gunId: "38-special",
      copGun: 3,
      deputyGun: 2,
    },
  ],
  dealers: [
    {
      id: "mama-dee",
      name: "Mama Dee",
      locationId: "bronx",
      drugIds: ["weed", "hashish", "ludes", "peyote"],
      traits: ["loyal", "connected"],
      greed: 30,
      violence: 35,
      loyalty: 85,
      paranoia: 35,
      connected: 65,
      toughness: 55,
      refuseBelow: -40,
      weaponGunId: "saturday-night-special",
      guardCount: 1,
    },
    {
      id: "needle-nick",
      name: "Needle Nick",
      locationId: "bronx",
      drugIds: ["heroin", "speed", "opium", "ludes"],
      traits: ["paranoid", "greedy"],
      greed: 70,
      violence: 55,
      loyalty: 30,
      paranoia: 75,
      connected: 35,
      toughness: 70,
      refuseBelow: -45,
      weaponGunId: "38-special",
      guardCount: 1,
    },
    {
      id: "rico",
      name: "Rico",
      locationId: "ghetto",
      drugIds: ["cocaine", "heroin", "pcp", "speed"],
      traits: ["violent", "proud"],
      greed: 55,
      violence: 85,
      loyalty: 35,
      paranoia: 50,
      connected: 45,
      toughness: 85,
      refuseBelow: -35,
      weaponGunId: "baretta",
      guardCount: 2,
    },
    {
      id: "professor-x",
      name: "Professor X",
      locationId: "central-park",
      drugIds: ["acid", "mda", "shrooms", "peyote"],
      traits: ["connected", "loyal"],
      greed: 25,
      violence: 25,
      loyalty: 70,
      paranoia: 45,
      connected: 85,
      toughness: 45,
      refuseBelow: -50,
      weaponGunId: "ruger",
      guardCount: 0,
    },
    {
      id: "big-paulie",
      name: "Big Paulie",
      locationId: "manhattan",
      drugIds: ["cocaine", "heroin", "opium", "mda", "pcp"],
      traits: ["greedy", "violent", "connected"],
      greed: 90,
      violence: 90,
      loyalty: 20,
      paranoia: 65,
      connected: 80,
      toughness: 105,
      refuseBelow: -30,
      weaponGunId: "38-special",
      guardCount: 3,
    },
    {
      id: "boardwalk-sal",
      name: "Boardwalk Sal",
      locationId: "coney-island",
      drugIds: ["weed", "hashish", "acid", "shrooms", "ludes"],
      traits: ["loyal", "proud"],
      greed: 45,
      violence: 50,
      loyalty: 75,
      paranoia: 35,
      connected: 35,
      toughness: 60,
      refuseBelow: -40,
      weaponGunId: "saturday-night-special",
      guardCount: 1,
    },
    {
      id: "brooklyn-rose",
      name: "Brooklyn Rose",
      locationId: "brooklyn",
      drugIds: ["cocaine", "speed", "mda", "pcp", "acid"],
      traits: ["paranoid", "connected"],
      greed: 60,
      violence: 65,
      loyalty: 45,
      paranoia: 80,
      connected: 70,
      toughness: 80,
      refuseBelow: -35,
      weaponGunId: "baretta",
      guardCount: 2,
    },
    {
      id: "queens-vic",
      name: "Queens Vic",
      locationId: "queens",
      drugIds: ["heroin", "opium", "weed", "hashish", "peyote"],
      traits: ["greedy", "loyal"],
      greed: 75,
      violence: 45,
      loyalty: 60,
      paranoia: 55,
      connected: 50,
      toughness: 72,
      refuseBelow: -45,
      weaponGunId: "ruger",
      guardCount: 1,
    },
    {
      id: "ferry-jo",
      name: "Ferry Jo",
      locationId: "staten-island",
      drugIds: ["weed", "ludes", "shrooms", "opium", "speed"],
      traits: ["loyal"],
      greed: 35,
      violence: 30,
      loyalty: 80,
      paranoia: 25,
      connected: 25,
      toughness: 50,
      refuseBelow: -50,
      weaponGunId: "saturday-night-special",
      guardCount: 0,
    },
    {
      id: "j-wood",
      name: "J-Wood",
      locationId: "west-end-halifax",
      drugIds: ["weed", "hashish", "ludes", "speed", "pcp"],
      traits: ["paranoid", "violent", "unpredictable"],
      greed: 55,
      violence: 88,
      loyalty: 18,
      paranoia: 92,
      connected: 48,
      toughness: 88,
      refuseBelow: -32,
      weaponGunId: "38-special",
      guardCount: 2,
      approachOffer: {
        id: "ultrasound",
        chance: 38,
        priceMin: 65,
        priceMax: 260,
        relationshipGain: 2,
        prompt: "%DEALER% pulls a cracked ultrasound wand from a Sobeys bag and offers you a scan for %PRICE%. \"No questions, no damn refunds, eh?\"",
        acceptMessage: "You pay %PRICE%. %DEALER% smears cold gel on your jacket and says the screen shows \"a tiny cop-shaped problem.\" Relationship +%RELATIONSHIP%.",
        declineMessage: "%DEALER% mutters that you are scared of science and wipes the wand on his sleeve, eh.",
        poorMessage: "%DEALER% says the ultrasound machine does not run on promises. You need %PRICE%, eh.",
      },
    },
  ],
  hobos: [
    {
      id: "tin-can-marty",
      name: "Tin Can Marty",
      locationId: "bronx",
      toughness: 22,
      trustThreshold: 24,
      fearThreshold: -35,
      intelQuality: 58,
      priceMin: 60,
      priceMax: 320,
      favoriteDrugIds: ["weed", "ludes"],
    },
    {
      id: "scratchy-lou",
      name: "Scratchy Lou",
      locationId: "ghetto",
      toughness: 38,
      trustThreshold: 30,
      fearThreshold: -45,
      intelQuality: 66,
      priceMin: 90,
      priceMax: 450,
      favoriteDrugIds: ["speed", "pcp"],
    },
    {
      id: "benchwise-eddie",
      name: "Benchwise Eddie",
      locationId: "central-park",
      toughness: 18,
      trustThreshold: 20,
      fearThreshold: -30,
      intelQuality: 72,
      priceMin: 75,
      priceMax: 360,
      favoriteDrugIds: ["acid", "shrooms"],
    },
    {
      id: "subway-sue",
      name: "Subway Sue",
      locationId: "manhattan",
      toughness: 30,
      trustThreshold: 35,
      fearThreshold: -50,
      intelQuality: 78,
      priceMin: 140,
      priceMax: 700,
      favoriteDrugIds: ["cocaine", "mda"],
    },
    {
      id: "boardwalk-benny",
      name: "Boardwalk Benny",
      locationId: "coney-island",
      toughness: 25,
      trustThreshold: 22,
      fearThreshold: -38,
      intelQuality: 60,
      priceMin: 55,
      priceMax: 300,
      favoriteDrugIds: ["weed", "hashish"],
    },
    {
      id: "stoop-annie",
      name: "Stoop Annie",
      locationId: "brooklyn",
      toughness: 34,
      trustThreshold: 28,
      fearThreshold: -42,
      intelQuality: 70,
      priceMin: 110,
      priceMax: 520,
      favoriteDrugIds: ["speed", "acid"],
    },
    {
      id: "rail-yard-ray",
      name: "Rail Yard Ray",
      locationId: "queens",
      toughness: 32,
      trustThreshold: 26,
      fearThreshold: -40,
      intelQuality: 64,
      priceMin: 95,
      priceMax: 430,
      favoriteDrugIds: ["opium", "peyote"],
    },
    {
      id: "ferry-dock-frank",
      name: "Ferry Dock Frank",
      locationId: "staten-island",
      toughness: 20,
      trustThreshold: 20,
      fearThreshold: -32,
      intelQuality: 54,
      priceMin: 50,
      priceMax: 260,
      favoriteDrugIds: ["ludes", "shrooms"],
    },
    {
      id: "chebucto-cam",
      name: "Chebucto Cam",
      locationId: "west-end-halifax",
      toughness: 26,
      trustThreshold: 24,
      fearThreshold: -36,
      intelQuality: 62,
      priceMin: 70,
      priceMax: 340,
      favoriteDrugIds: ["weed", "speed"],
    },
  ],
  subwaySayings: [
    "Wouldn't it be funny if everyone suddenly quacked at once, eh?",
    "The Pope was once Jewish, you know",
    "I'll bet you have some really damn interesting dreams, eh",
    "So I think I'm going to Amsterdam this year",
    "Son, you need a yellow haircut",
    "Does your mother know you're a damn dope dealer, eh?",
    "Are you high on something?",
    "There is nothing like having a shitload of money, eh",
    "We're winning the war for drugs!",
    "Drugs can be your friend, eh!",
  ],
  playing: [
    "`Are you Experienced` by Jimi Hendrix",
    "`Cheeba Cheeba` by Tone Loc",
    "`Comin` in to Los Angeles` by Arlo Guthrie",
    "`White Rabbit` by Jefferson Airplane",
    "`Acapulco Gold` by Riders of the Purple Sage",
  ],
  stoppedTo: [
    "have a beer",
    "smoke a joint",
    "smoke a cigar",
    "smoke a Djarum",
    "smoke a cigarette",
  ],
};
