import type { GameConfig } from "./types";

export const DEFAULT_GAME_CONFIG: GameConfig = {
  version: "faithful-0.5-hrm-weapons",
  startDate: "1984-12-01",
  numTurns: 31,
  startCash: 2000,
  startDebt: 5500,
  startBank: 0,
  startHealth: 100,
  startHelpers: 8,
  baseSpace: 20,
  helperSpace: 10,
  debtInterest: 10,
  bankInterest: 5,
  playerArmor: 100,
  helperArmor: 50,
  fightTimeoutSeconds: 5,
  llmDialogue: {
    enabled: true,
    endpoint: "http://127.0.0.1:11434",
    healthCheckTimeoutMs: 2_000,
    maxTokens: 80,
    model: "llama3.1:8b",
    temperature: 0.85,
    timeoutMs: 20_000,
  },
  currency: {
    symbol: "$",
    prefix: true,
  },
  names: {
    helperSingular: "bitch",
    helperPlural: "bitches",
    gunSingular: "weapon",
    gunPlural: "weapons",
    drugSingular: "drug",
    drugPlural: "drugs",
    loanShark: "the Loan Shark",
    bank: "the Bank",
    gunShop: "Sackville Salvage & Sporting Goods",
    roughPub: "the pub",
  },
  prices: {
    spy: 20000,
    tipoff: 10000,
    helperMin: 50000,
    helperMax: 150000,
  },
  drugsMeta: {
    expensiveMessageA: "Sorry, cops made a big %DRUG% bust! Prices are outrageous!",
    expensiveMessageB: "Buyers are paying ridiculous damn money for %DRUG%, my guy!",
    cheapDivide: 4,
    expensiveMultiply: 4,
  },
  serviceLocations: {
    loanShark: "downtown-halifax",
    bank: "downtown-halifax",
    gunShop: "sackville",
    roughPub: "spryfield",
  },
  locations: [
    { id: "downtown-halifax", name: "Downtown Halifax", policePresence: 75, minDrug: 4, maxDrug: 10 },
    { id: "north-end-halifax", name: "North End Halifax", policePresence: 35, minDrug: 6, maxDrug: 12 },
    { id: "west-end-halifax", name: "West End Halifax", policePresence: 12, minDrug: 6, maxDrug: 10 },
    { id: "dartmouth", name: "Dartmouth", policePresence: 45, minDrug: 6, maxDrug: 12 },
    { id: "bedford", name: "Bedford", policePresence: 30, minDrug: 5, maxDrug: 10 },
    { id: "sackville", name: "Sackville", policePresence: 22, minDrug: 7, maxDrug: 12 },
    { id: "spryfield", name: "Spryfield", policePresence: 28, minDrug: 7, maxDrug: 12 },
    { id: "halifax-public-gardens", name: "Halifax Public Gardens", policePresence: 50, minDrug: 5, maxDrug: 11 },
    { id: "eastern-passage", name: "Eastern Passage", policePresence: 18, minDrug: 6, maxDrug: 12 },
  ],
  drugs: [
    {
      id: "acid",
      name: "Acid",
      minPrice: 1000,
      maxPrice: 4400,
      cheap: true,
      expensive: false,
      cheapMessage: "The market is flooded with cheap home-made acid!",
    },
    {
      id: "cocaine",
      name: "Cocaine",
      minPrice: 15000,
      maxPrice: 29000,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "hashish",
      name: "Hashish",
      minPrice: 480,
      maxPrice: 1280,
      cheap: true,
      expensive: false,
      cheapMessage: "The Marrakesh Express has arrived!",
    },
    {
      id: "heroin",
      name: "Heroin",
      minPrice: 5500,
      maxPrice: 13000,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "ludes",
      name: "Ludes",
      minPrice: 11,
      maxPrice: 60,
      cheap: true,
      expensive: false,
      cheapMessage: "Rival drug dealers raided a pharmacy and are selling cheap ludes!",
    },
    {
      id: "mda",
      name: "MDA",
      minPrice: 1500,
      maxPrice: 4400,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "opium",
      name: "Opium",
      minPrice: 540,
      maxPrice: 1250,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "pcp",
      name: "PCP",
      minPrice: 1000,
      maxPrice: 2500,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "peyote",
      name: "Peyote",
      minPrice: 220,
      maxPrice: 700,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "shrooms",
      name: "Shrooms",
      minPrice: 630,
      maxPrice: 1300,
      cheap: false,
      expensive: false,
      cheapMessage: "",
    },
    {
      id: "speed",
      name: "Speed",
      minPrice: 90,
      maxPrice: 250,
      cheap: false,
      expensive: true,
      cheapMessage: "",
    },
    {
      id: "weed",
      name: "Weed",
      minPrice: 315,
      maxPrice: 890,
      cheap: true,
      expensive: false,
      cheapMessage: "Colombian freighter dusted the Coast Guard! Weed prices have bottomed out!",
    },
  ],
  guns: [
    { id: "glass-coke-bottle", name: "Glass Coke-a-Cola Bottle", price: 900, space: 1, damage: 2 },
    { id: "tire-iron", name: "Tire Iron", price: 1400, space: 2, damage: 4 },
    { id: "fillet-knife", name: "Rusty Fillet Knife", price: 1800, space: 1, damage: 3 },
    { id: "ruger", name: "Sharpened Hockey Stick", price: 2200, space: 3, damage: 4 },
    { id: "baretta", name: "Sock Full of Loonies", price: 2500, space: 2, damage: 5 },
    { id: "saturday-night-special", name: "Zamboni-Part Mace", price: 3300, space: 5, damage: 7 },
    { id: "38-special", name: "Bow and Arrow", price: 3600, space: 4, damage: 9 },
  ],
  merchants: [
    {
      id: "sackville-salvage",
      name: "Sackville Salvage & Sporting Goods",
      locationId: "sackville",
      gunIds: ["glass-coke-bottle", "tire-iron", "fillet-knife", "ruger", "baretta", "saturday-night-special", "38-special"],
      markup: 100,
      bid: 72,
    },
    {
      id: "north-end-junk-counter",
      name: "North End Junk Counter",
      locationId: "north-end-halifax",
      gunIds: ["glass-coke-bottle", "fillet-knife", "ruger"],
      markup: 92,
      bid: 64,
    },
    {
      id: "spryfield-swap-table",
      name: "Spryfield Swap Table",
      locationId: "spryfield",
      gunIds: ["tire-iron", "baretta", "saturday-night-special"],
      markup: 108,
      bid: 76,
    },
    {
      id: "dartmouth-sporting-shelf",
      name: "Dartmouth Sporting Shelf",
      locationId: "dartmouth",
      gunIds: ["fillet-knife", "ruger", "38-special"],
      markup: 118,
      bid: 78,
    },
    {
      id: "dockside-barter-crate",
      name: "Dockside Barter Crate",
      locationId: "eastern-passage",
      gunIds: ["glass-coke-bottle", "tire-iron", "fillet-knife"],
      markup: 86,
      bid: 58,
    },
  ],
  cops: [
    {
      id: "hardass",
      name: "Officer Hardass",
      deputyName: "deputy",
      deputiesName: "deputies",
      armor: 4,
      deputyArmor: 3,
      attackPenalty: 30,
      defendPenalty: 30,
      minDeputies: 2,
      maxDeputies: 8,
      gunId: "baretta",
      copGun: 1,
      deputyGun: 1,
    },
    {
      id: "bob",
      name: "Officer Bob",
      deputyName: "deputy",
      deputiesName: "deputies",
      armor: 15,
      deputyArmor: 4,
      attackPenalty: 30,
      defendPenalty: 20,
      minDeputies: 4,
      maxDeputies: 10,
      gunId: "baretta",
      copGun: 2,
      deputyGun: 1,
    },
    {
      id: "smith",
      name: "Agent Smith",
      deputyName: "cop",
      deputiesName: "cops",
      armor: 50,
      deputyArmor: 6,
      attackPenalty: 20,
      defendPenalty: 20,
      minDeputies: 6,
      maxDeputies: 18,
      gunId: "38-special",
      copGun: 3,
      deputyGun: 2,
    },
  ],
  dealers: [
    {
      id: "mama-dee",
      name: "Mama Dee",
      locationId: "north-end-halifax",
      drugIds: ["weed", "hashish", "ludes", "peyote"],
      traits: ["loyal", "connected"],
      greed: 30,
      violence: 35,
      loyalty: 85,
      paranoia: 35,
      connected: 65,
      toughness: 55,
      refuseBelow: -40,
      weaponGunId: "saturday-night-special",
      guardCount: 1,
    },
    {
      id: "needle-nick",
      name: "Needle Nick",
      locationId: "north-end-halifax",
      drugIds: ["heroin", "speed", "opium", "ludes"],
      traits: ["paranoid", "greedy"],
      greed: 70,
      violence: 55,
      loyalty: 30,
      paranoia: 75,
      connected: 35,
      toughness: 70,
      refuseBelow: -45,
      weaponGunId: "38-special",
      guardCount: 1,
    },
    {
      id: "rico",
      name: "Rico",
      locationId: "spryfield",
      drugIds: ["cocaine", "heroin", "pcp", "speed"],
      traits: ["violent", "proud"],
      greed: 55,
      violence: 85,
      loyalty: 35,
      paranoia: 50,
      connected: 45,
      toughness: 85,
      refuseBelow: -35,
      weaponGunId: "baretta",
      guardCount: 2,
    },
    {
      id: "professor-x",
      name: "Professor X",
      locationId: "halifax-public-gardens",
      drugIds: ["acid", "mda", "shrooms", "peyote"],
      traits: ["connected", "loyal"],
      greed: 25,
      violence: 25,
      loyalty: 70,
      paranoia: 45,
      connected: 85,
      toughness: 45,
      refuseBelow: -50,
      weaponGunId: "ruger",
      guardCount: 0,
    },
    {
      id: "big-paulie",
      name: "Shady Rich",
      locationId: "downtown-halifax",
      drugIds: ["cocaine", "heroin", "opium", "mda", "pcp"],
      traits: ["greedy", "paranoid", "conspiracy"],
      greed: 82,
      violence: 68,
      loyalty: 20,
      paranoia: 96,
      connected: 72,
      toughness: 88,
      refuseBelow: -30,
      weaponGunId: "tire-iron",
      guardCount: 2,
    },
    {
      id: "sweet-aidan",
      name: "Sweet Aidan",
      locationId: "downtown-halifax",
      drugIds: ["acid", "speed", "ludes", "hashish", "shrooms"],
      traits: ["sketchy", "paranoid", "connected"],
      greed: 58,
      violence: 42,
      loyalty: 18,
      paranoia: 88,
      connected: 66,
      toughness: 54,
      refuseBelow: -42,
      weaponGunId: "glass-coke-bottle",
      guardCount: 0,
      dialogueLines: [
        "Sweet Aidan asks if you know why bismuth crystals grow stair-step towers before he quotes the price, my guy.",
        "Sweet Aidan wants to know whether the Halifax Explosion changed the taste of the rain, eh.",
        "Sweet Aidan squints and asks if numbers stations still hum on shortwave before counting your cash.",
        "Sweet Aidan says Cold War microphones hid in everyday junk, then asks what you are buying.",
        "Sweet Aidan wonders if the moon smells like burnt matches and if you brought exact change.",
      ],
    },
    {
      id: "boardwalk-sal",
      name: "Boardwalk Sal",
      locationId: "dartmouth",
      drugIds: ["weed", "hashish", "acid", "shrooms", "ludes"],
      traits: ["loyal", "proud"],
      greed: 45,
      violence: 50,
      loyalty: 75,
      paranoia: 35,
      connected: 35,
      toughness: 60,
      refuseBelow: -40,
      weaponGunId: "saturday-night-special",
      guardCount: 1,
    },
    {
      id: "brooklyn-rose",
      name: "Bedford Rose",
      locationId: "bedford",
      drugIds: ["cocaine", "speed", "mda", "pcp", "acid"],
      traits: ["paranoid", "connected"],
      greed: 60,
      violence: 65,
      loyalty: 45,
      paranoia: 80,
      connected: 70,
      toughness: 80,
      refuseBelow: -35,
      weaponGunId: "baretta",
      guardCount: 2,
    },
    {
      id: "queens-vic",
      name: "Sackville Vic",
      locationId: "sackville",
      drugIds: ["heroin", "opium", "weed", "hashish", "peyote"],
      traits: ["greedy", "loyal"],
      greed: 75,
      violence: 45,
      loyalty: 60,
      paranoia: 55,
      connected: 50,
      toughness: 72,
      refuseBelow: -45,
      weaponGunId: "ruger",
      guardCount: 1,
    },
    {
      id: "ferry-jo",
      name: "Ferry Jo",
      locationId: "eastern-passage",
      drugIds: ["weed", "ludes", "shrooms", "opium", "speed"],
      traits: ["loyal"],
      greed: 35,
      violence: 30,
      loyalty: 80,
      paranoia: 25,
      connected: 25,
      toughness: 50,
      refuseBelow: -50,
      weaponGunId: "saturday-night-special",
      guardCount: 0,
    },
    {
      id: "j-wood",
      name: "J-Wood",
      locationId: "west-end-halifax",
      drugIds: ["weed", "hashish", "ludes", "speed", "pcp"],
      traits: ["paranoid", "violent", "unpredictable"],
      greed: 55,
      violence: 88,
      loyalty: 18,
      paranoia: 92,
      connected: 48,
      toughness: 88,
      refuseBelow: -32,
      weaponGunId: "38-special",
      guardCount: 2,
      approachOffer: {
        id: "ultrasound",
        chance: 38,
        priceMin: 65,
        priceMax: 260,
        relationshipGain: 2,
        prompt: "%DEALER% pulls a cracked ultrasound wand from a Sobeys bag and offers you a scan for %PRICE%. \"No questions, no damn refunds, my guy?\"",
        acceptMessage: "You pay %PRICE%. %DEALER% smears cold gel on your jacket and says the screen shows \"a tiny cop-shaped problem.\" Relationship +%RELATIONSHIP%.",
        declineMessage: "%DEALER% mutters that you are scared of science and wipes the wand on his sleeve, eh.",
        poorMessage: "%DEALER% says the ultrasound machine does not run on promises. You need %PRICE%, eh.",
      },
    },
  ],
  hobos: [
    {
      id: "tin-can-marty",
      name: "Tin Can Marty",
      locationId: "north-end-halifax",
      dialogStyle: "hoser",
      toughness: 22,
      trustThreshold: 24,
      fearThreshold: -35,
      intelQuality: 58,
      priceMin: 60,
      priceMax: 320,
      favoriteDrugIds: ["weed", "ludes"],
    },
    {
      id: "scratchy-lou",
      name: "Scratchy Lou",
      locationId: "spryfield",
      toughness: 38,
      trustThreshold: 30,
      fearThreshold: -45,
      intelQuality: 66,
      priceMin: 90,
      priceMax: 450,
      favoriteDrugIds: ["speed", "pcp"],
    },
    {
      id: "benchwise-eddie",
      name: "Benchwise Eddie",
      locationId: "halifax-public-gardens",
      toughness: 18,
      trustThreshold: 20,
      fearThreshold: -30,
      intelQuality: 72,
      priceMin: 75,
      priceMax: 360,
      favoriteDrugIds: ["acid", "shrooms"],
    },
    {
      id: "subway-sue",
      name: "Barrington Sue",
      locationId: "downtown-halifax",
      toughness: 30,
      trustThreshold: 35,
      fearThreshold: -50,
      intelQuality: 78,
      priceMin: 140,
      priceMax: 700,
      favoriteDrugIds: ["cocaine", "mda"],
    },
    {
      id: "shanobi",
      name: "Shanobi",
      locationId: "downtown-halifax",
      dialogStyle: "rhyme",
      toughness: 24,
      trustThreshold: 26,
      fearThreshold: -34,
      intelQuality: 68,
      priceMin: 80,
      priceMax: 420,
      favoriteDrugIds: ["weed", "hashish"],
    },
    {
      id: "boardwalk-benny",
      name: "Boardwalk Benny",
      locationId: "dartmouth",
      toughness: 25,
      trustThreshold: 22,
      fearThreshold: -38,
      intelQuality: 60,
      priceMin: 55,
      priceMax: 300,
      favoriteDrugIds: ["weed", "hashish"],
    },
    {
      id: "stoop-annie",
      name: "Stoop Annie",
      locationId: "bedford",
      toughness: 34,
      trustThreshold: 28,
      fearThreshold: -42,
      intelQuality: 70,
      priceMin: 110,
      priceMax: 520,
      favoriteDrugIds: ["speed", "acid"],
    },
    {
      id: "rail-yard-ray",
      name: "Rail Yard Ray",
      locationId: "sackville",
      toughness: 32,
      trustThreshold: 26,
      fearThreshold: -40,
      intelQuality: 64,
      priceMin: 95,
      priceMax: 430,
      favoriteDrugIds: ["opium", "peyote"],
    },
    {
      id: "ferry-dock-frank",
      name: "Ferry Dock Frank",
      locationId: "eastern-passage",
      dialogStyle: "hoser",
      toughness: 20,
      trustThreshold: 20,
      fearThreshold: -32,
      intelQuality: 54,
      priceMin: 50,
      priceMax: 260,
      favoriteDrugIds: ["ludes", "shrooms"],
    },
    {
      id: "chebucto-cam",
      name: "Chebucto Cam",
      locationId: "west-end-halifax",
      dialogStyle: "hoser",
      toughness: 26,
      trustThreshold: 24,
      fearThreshold: -36,
      intelQuality: 62,
      priceMin: 70,
      priceMax: 340,
      favoriteDrugIds: ["weed", "speed"],
    },
  ],
  subwaySayings: [
    "Wouldn't it be funny if everyone suddenly quacked at once, eh?",
    "The Pope was once Jewish, you know",
    "I'll bet you have some really damn interesting dreams, my guy",
    "So I think I'm going to Amsterdam this year",
    "Son, you need a yellow haircut",
    "Does your mother know you're a damn dope dealer, eh?",
    "Are you high on something?",
    "There is nothing like having a shitload of money, eh",
    "We're winning the war for drugs!",
    "Drugs can be your friend, my guy!",
  ],
  playing: [
    "`Are you Experienced` by Jimi Hendrix",
    "`Cheeba Cheeba` by Tone Loc",
    "`Comin` in to Los Angeles` by Arlo Guthrie",
    "`White Rabbit` by Jefferson Airplane",
    "`Acapulco Gold` by Riders of the Purple Sage",
  ],
  stoppedTo: [
    "have a beer",
    "smoke a joint",
    "smoke a cigar",
    "smoke a Djarum",
    "smoke a cigarette",
  ],
};
